# Generated by Django 5.0.7 on 2024-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_customusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={},
        ),
    ]
