# Generated by Django 5.0.7 on 2024-07-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_customusers_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customUsers',
            new_name='Users',
        ),
    ]
