# Generated by Django 5.0.7 on 2024-07-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_registration_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('auto', 'Auto'), ('bike', 'Bike')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
