# Generated by Django 5.0.7 on 2024-07-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_driverprofile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
