# Generated by Django 5.0.7 on 2024-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_ride_driver_feedback_ride_driver_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='driver_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rider_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
