# Generated by Django 5.0.7 on 2024-07-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_users_delete_myuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='customUsers',
        ),
    ]
