# Generated by Django 5.0.7 on 2024-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_users_name_users_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='driver_license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], default='', max_length=10),
        ),
    ]
