# Generated by Django 5.0.7 on 2024-07-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_driver_license_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='driver_license',
        ),
    ]
