# Generated by Django 5.0.7 on 2024-07-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_driverprofile_profile_picture'),
    ]

   
