# Generated by Django 5.0.7 on 2024-07-14 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_driverprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(default='', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('auto', 'Auto'), ('car', 'Car'), ('bike', 'Bike')], default='', max_length=50)),
                ('vehicle_registration_number', models.CharField(default='', max_length=20)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
