# Generated by Django 5.0.7 on 2024-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_driverprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
