# Generated by Django 5.0.7 on 2024-07-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_driverprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('rider', 'Rider')], default='', max_length=10),
        ),
    ]
