# Generated by Django 5.0.7 on 2024-07-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_driverprofile_location_driverprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('auto', 'Auto'), ('bike', 'Bike')], default='car', max_length=50),
        ),
    ]
