# Generated by Django 5.0.7 on 2024-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_users_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
