# Generated by Django 5.0.7 on 2024-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_alter_ride_driver_rating_alter_ride_rider_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='drop_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
