# Generated by Django 5.0.7 on 2024-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_ride_drop_latitude_ride_drop_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
